version = 0.1
[default.deploy.parameters]
stack_name = "github-actions-react-s3"
resolve_s3 = true
s3_prefix = "github-actions-react-s3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
