name: CDK Based IaC Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - cdk/**
  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - cdk/**

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup CDK
        run: |
          npm install -g aws-cdk

      - name: Check template for errors
        run: | 
          cd ${{ github.workspace }}/cdk
          npm ci
          cdk synth --require-approval=never --ci --all

