name: React App Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ['frontend/public/**', 'frontend/src/**', 'frontend/package*.json', 'frontend/index.html']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.x'

      - name: Restoring Frontend Packages
        working-directory: ./frontend
        run: npm ci

      - name: Frontend Build
        working-directory: ./frontend
        run: npm run build

      # no tests currently... restore if you want to run some
      - name: Run Test Suite
        working-directory: ./frontend
        run: npm run test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync frontend/dist s3://gha-poc-stack-site-bucket --delete
