name: React App Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - frontend/**

  pull_request:
    types: [ opened, reopened, synchronize ]
    paths:
      - frontend/index.html
      - frontend/public/**
      - frontend/src/**
      - frontend/package*.json
env:
  FRONTEND_BASE_DIR: ./frontend
  FRONTEND_DIST_DIR: ./frontend/dist

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.x'

      - name: Restoring Frontend Packages
        working-directory: ${{ env.FRONTEND_BASE_DIR }}
        run: npm ci

      - name: Frontend Build
        working-directory: ${{ env.FRONTEND_BASE_DIR }}
        run: npm run build

      # no tests currently... restore if you want to run some
      - name: Run Test Suite
        working-directory: ${{ env.FRONTEND_BASE_DIR }}
        run: npm run test

      - name: Configure AWS Credentials
        if: github.ref_name == 'main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3 bucket
        if: github.ref_name == 'main'
        run: |
          aws s3 sync ${{ env.FRONTEND_DIST_DIR }} s3://gha-poc-stack-site-bucket --delete
