name: React CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ['public/**', 'src/**', 'package*.json', 'index.html']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.x]

    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      # no tests currently... restore if you want to run some
      # - run: npx vitest

      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3 bucket
        run: |
          aws s3 sync dist s3://github-actions-react-s3-github-actions-react-s3 --delete

      - name: Show Deployment Stack Information
        run: |
          sam list stack-outputs --stack-name github-actions-react-s3