name: IaC Pipeline for Static Site

on:
  push:
    branches: ["main"]
    paths: ['aws-sam/**']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.x]

    steps:
      - uses: actions/checkout@v1
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # sam build
      - run: sam build --use-container --build-image amazon/aws-sam-cli-build-image-nodejs20.x:latest --config-file ./aws-sam/samconfig.toml --template-file ./aws-sam/template.yml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

